language: node_js

node_js:
  - "8"

dist: trusty

addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

notifications:
  email: false

cache:
  directories:
    - node_modules

# allow headful tests
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - google-chrome-stable --headless --no-sandbox --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - rm package-lock.json
  - npm i tape tap-spec puppeteer isomorphic-fetch

script:
  - npm test
