sudo: required

language: node_js

node_js:
  - "8"

addons:
  chrome: stable

notifications:
  email: false

# allow headful tests
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - rm package-lock.json
  - npm i os tape tap-spec puppeteer isomorphic-fetch express epha/domain-akte epha/domain-assets

script:
  - npm test
