language: node_js
node_js:
  - "9"
dist: trusty
sudo: true
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn add tape tap-spec puppeteer isomorphic-fetch
script:
  - yarn test
