language: node_js

dist: trusty

addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

notifications:
  email: false

cache:
  directories:
    - node_modules

# allow headful tests
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - rm package-lock.json
  - npm i tape tap-spec pupeteer isomorphic-fetch

script:
  - npm test
