sudo: false

language: node_js

node_js:
  - "8"

addons:
  chrome: stable
  
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - rm package-lock.json
  - npm i tape tap-spec puppeteer isomorphic-fetch

script:
  - npm test
